learning_users/basicapp/urls.py
from django.urls import path
from . import views

app_name = "basicapp"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("user_login/", views.user_login, name="user_login"),
    path("logout/", views.user_logout, name="logout"),
    path("special/", views.special, name="special"),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("basicapp/", include("basicapp.urls")),
]

learning_users/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site=models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
        return self.user.username

learning_users/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basicapp/views.py
from urllib import request

from urllib import request

from django.shortcuts import render
from basicapp.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'basicapp/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in. Nice!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basicapp/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed.")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'basicapp/login.html', {})

learning_users/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Learning Users</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index'%}">Django</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#mainNav" aria-controls="mainNav"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="mainNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'basicapp:register' %}">Register</a>
        </li>

        {% if user.is_authenticated %}
     
        <li class="nav-item">
        <a class="nav-link" href="{% url 'basicapp:logout' %}">Logout</a>        
      </li>
        {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'basicapp:user_login' %}">Login</a>        
      </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

{%block body_block%}
{%endblock%}
    </body>
</html>

learning_users/templates/basicapp/index.html
{% extends "basicapp/base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to the Learning Users App</h1>
        <p>This is the main index page for the Learning Users application.</p>
    </div>
{% endblock %}

learning_users/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}

{% block body_block%}
<div class="jumbotron">
    <h1>Login</h1>
    <p>Please enter your username and password to log in.</p>
    <form method="post" action="{% url 'basicapp:user_login' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter username" required>

            <label for="password">Password:</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" required>

            <button type="submit" class="btn btn-primary mt-3">Login</button>
        </div>
    </form>
</div>

{% endblock %}

learning_users/templates/basicapp/registration.html
{% extends "basicapp/base.html" %}
{% load static %}
{% block body_block %}
    <div class="jumbotron">

        {% if registered %}
            <p>You have successfully registered! You can now <a href="{% url 'basicapp:login' %}">log in</a>.</p>
        {% else %}
        <h1> Register Here</h1>
        <h3> Please fill out the form below to register for an account.</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <button type="submit" class="btn btn-primary">Register</button>
            </form>
{% endif %}
    </div>
{% endblock %}